### ISSUE TITLE
About overlap_zones in S02

### ISSUE THREAD

**Issue by zyf-bit** [kamkyu94/Fast_Online_MTMCT#4]
Hello, authors.
I downloaded this project and found only the overlap zones of the S02 scenario.
Do you know how to obtain overlap zones in other scenarios?
Does missing overlap zones affect the accuracy of the program?
Looking forward to receiving your reply
![image](https://github.com/user-attachments/assets/12cc32a3-bb6e-4e4d-8d29-8c81802b0601)

**Comment by kamkyu94** [comment]
Hello.

The overlap zones are manually drawn with Adobe Photoshop.
You may draw the overlap zones for other scenarios if you needed.

Also, although I haven't exactly compared, but I probably think that missing the overlap zones would affect the accuracy.

Sorry for late reply, and thank you for your attention.
